version: "3.8"

services:
  mysqldb:
    image: mysql:8.0 # Mise à jour vers MySQL 8.0 pour correspondre au connecteur mysql-connector-j-8.0.31
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: malek
      MYSQL_DATABASE: kaddemdb
    ports:
      - "3306:3306" # Expose le port 3306 pour un accès externe si nécessaire
    volumes:
      - db:/var/lib/mysql
    networks:
      - kaddem-network

  app-kaddem:
    depends_on:
      - mysqldb # Assure que MySQL démarre avant l'application
    image: malekswissi11/testdevops:${DOCKER_IMAGE_TAG} # Utilise l'image de votre pipeline Jenkins
    restart: on-failure
    ports:
      - "8082:8080" # Mappe le port 8082 de l'hôte au port 8080 du conteneur (port par défaut de Spring Boot)
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddemdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "malek",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.port": "8080"
      }'
    stdin_open: true
    tty: true
    networks:
      - kaddem-network

volumes:
  db:

networks:
  kaddem-network:
    driver: bridge
